version: '2'

services:
  bot:
    build: .
    networks:
      - internal
    volumes:
      - bot-log:/brisebois/log
    depends_on:
      - mongo

  mongo:
    image: mongo:3.6-jessie
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: changeit
    networks:
      - internal
    volumes:
      - ./mongo:/docker-entrypoint-initdb.d/
      - mongo-conf:/data/configdb
      - mongo-data:/data/db

networks:
  internal:
    driver: bridge

volumes:
  bot-log: {}
  mongo-conf: {}
  mongo-data: {}
